# Generated by Django 5.2.8 on 2026-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ubno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
