# Generated by Django 5.2.8 on 2026-02-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_ubno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='max_books',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reader',
            name='membership',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=10),
        ),
    ]
