# Generated by Django 5.2.8 on 2026-02-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_reader_max_books_reader_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='max_books',
            new_name='issue_limit',
        ),
        migrations.AlterField(
            model_name='reader',
            name='membership',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='BASIC', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='issuebook',
            constraint=models.UniqueConstraint(fields=('book', 'reader', 'is_returned'), name='unique_active_issue'),
        ),
    ]
